name: Build, Push, and Run Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cipipelinetest:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cipipelinetest:latest

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cipipelinetest:latest

      - name: Run Docker container
        run: |
          docker run --name my-container -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/cipipelinetest:latest || exit 1

      - name: Verify container is running
        run: docker ps -a
        
      - name: Clean up
        run: |
          docker stop my-container || echo "Container is not running or does not exist."
          docker rm my-container || echo "Failed to remove container."
